# Generated by Django 4.2.7 on 2023-12-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='what_got_saled',
            field=models.CharField(blank=True, choices=[], max_length=250, null=True, verbose_name='المنتج'),
        ),
    ]
