# Generated by Django 4.2.7 on 2023-12-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sales_what_got_saled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='what_got_saled',
        ),
        migrations.AddField(
            model_name='products',
            name='got_it_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تم شرائه من'),
        ),
    ]
