# Generated by Django 4.2.7 on 2023-12-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sales_what_got_saled_products_got_it_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='what_got_saled',
            field=models.CharField(blank=True, choices=[], max_length=250, null=True, verbose_name='المنتج'),
        ),
    ]
