# Generated by Django 4.2.7 on 2023-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_products_got_it_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='what_got_saled',
            field=models.CharField(blank=True, choices=[('اعلاف سردينة', 'اعلاف سردينة')], max_length=250, null=True, verbose_name='المنتج'),
        ),
    ]
