# Generated by Django 4.2.7 on 2023-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sales_what_got_saled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='who_bought',
            field=models.CharField(blank=True, choices=[], max_length=250, null=True, verbose_name='الزبون'),
        ),
        migrations.AlterField(
            model_name='products',
            name='salary',
            field=models.FloatField(default=0, verbose_name='سعره للواحد'),
        ),
    ]
