# Generated by Django 4.2.7 on 2023-12-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sales_who_bought_alter_products_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='who_bought',
            field=models.CharField(blank=True, choices=[('محمد العوادي', 'محمد العوادي')], max_length=250, null=True, verbose_name='الزبون'),
        ),
    ]
