# Generated by Django 4.2.7 on 2023-12-25 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sales_who_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
