# Generated by Django 5.0 on 2023-12-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sales_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='what_got_saled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='who_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.zabon', verbose_name='الزبون'),
        ),
    ]
