# Generated by Django 5.0 on 2023-12-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sales_what_got_saled_alter_sales_who_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='got_it_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.saler', verbose_name='تم شرائه من'),
        ),
    ]
