# Generated by Django 5.0 on 2023-12-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_products_got_it_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='fwater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='saler',
            name='isdeb',
            field=models.BooleanField(default=False, verbose_name='دائن؟'),
        ),
        migrations.AddField(
            model_name='zabon',
            name='isdeb',
            field=models.BooleanField(default=False, verbose_name='مدين؟'),
        ),
    ]
