# Generated by Django 5.0 on 2023-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fwater_saler_isdeb_zabon_isdeb'),
    ]

    operations = [
        migrations.AddField(
            model_name='saler',
            name='how_much',
            field=models.FloatField(default=0),
        ),
    ]
