# Generated by Django 5.0 on 2023-12-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_saler_how_much'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabon',
            name='how_muchd',
            field=models.FloatField(default=0),
        ),
    ]
