# Generated by Django 5.0 on 2023-12-26 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_zabon_how_muchd'),
    ]

    operations = [
        migrations.AddField(
            model_name='fwater',
            name='description_fwater',
            field=models.TextField(blank=True, null=True, verbose_name='السبب'),
        ),
        migrations.AddField(
            model_name='fwater',
            name='how_many_fwater',
            field=models.FloatField(default=0, verbose_name='مقدار الفاتورة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fwater',
            name='time_added_fwater',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='وقت اضافة الفاتورة'),
        ),
        migrations.AlterField(
            model_name='saler',
            name='how_much',
            field=models.FloatField(default=0, verbose_name='المقدار'),
        ),
        migrations.AlterField(
            model_name='zabon',
            name='how_muchd',
            field=models.FloatField(default=0, verbose_name='المقدار'),
        ),
    ]
