# Generated by Django 5.0 on 2023-12-26 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fwater_description_fwater_fwater_how_many_fwater_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fwater',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': 'فواتير'},
        ),
        migrations.AlterField(
            model_name='fwater',
            name='time_added_fwater',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='وقت اضافة الفاتورة'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='وقت الاضافة'),
        ),
    ]
