# Generated by Django 5.0 on 2024-01-08 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_fwater_options_alter_fwater_time_added_fwater_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المحل')),
                ('addr', models.TextField(blank=True, null=True, verbose_name='عنوان المحل')),
            ],
            options={
                'verbose_name': 'المحل',
                'verbose_name_plural': 'المحلات',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='shop_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shop', verbose_name='المحل'),
        ),
    ]
