# Generated by Django 5.0 on 2024-01-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_factory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'مصنع', 'verbose_name_plural': 'المصانع'},
        ),
    ]
