# Generated by Django 5.0 on 2024-02-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_factory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='deduction',
            field=models.FloatField(default=0, verbose_name='خصومات'),
        ),
    ]
