# Generated by Django 4.2.7 on 2023-12-19 19:00

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
            ],
            options={
                'verbose_name': 'المجموعات',
                'verbose_name_plural': 'مجموعات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'verbose_name': 'الحسابات الشخصية للموقع',
                'verbose_name_plural': 'الحسابات الشخصية للموقع',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='دخله الشهري')),
                ('name', models.CharField(max_length=250, verbose_name='الإسم')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=250, verbose_name='الجنس')),
                ('phone_nu', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('id_for', models.CharField(blank=True, max_length=250, null=True, verbose_name='الرقم القومي')),
                ('date_ofj', models.DateField(default=datetime.datetime.now)),
                ('the_acc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الحساب الشخصي على الموقع')),
            ],
            options={
                'verbose_name_plural': 'الأشخاص',
            },
        ),
    ]
