# Generated by Django 5.0 on 2023-12-26 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='pers_pho',
            field=models.ImageField(blank=True, upload_to='emp_photos', verbose_name='رفع صورة شخصية'),
        ),
        migrations.AlterField(
            model_name='acc',
            name='date_ofj',
            field=models.DateField(default=datetime.datetime.now, verbose_name='وقت انضمامة للعمل'),
        ),
    ]
