# Generated by Django 5.0 on 2024-01-06 00:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_acc_pers_pho_alter_acc_date_ofj'),
    ]

    operations = [
        migrations.CreateModel(
            name='absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmd', models.FloatField(verbose_name='عدد ايام الغياب')),
                ('startdate', models.DateField(default=datetime.datetime.now, verbose_name='يبدأ من يوم')),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.acc', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'غائب',
                'verbose_name_plural': 'غيابات',
            },
        ),
    ]
