# Generated by Django 5.0 on 2024-02-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_absent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'الحسابات الشخصية ', 'verbose_name_plural': 'الحسابات الشخصية '},
        ),
    ]
